context("StructuredXStringSet")
test_that("StructuredXStringSet:",{
  data("dbs", package = "Structstrings", envir = environment())
  data("seq", package = "Structstrings", envir = environment())
  seq <- RNAStringSet(seq)
  sdbs <- StructuredRNAStringSet(unname(seq),dbs)
  expect_s4_class(sdbs,"StructuredRNAStringSet")
  expect_named(sdbs,names(dbs))
  sdbs <- StructuredRNAStringSet(seq,dbs)
  expect_s4_class(sdbs,"StructuredRNAStringSet")
  expect_named(sdbs,names(seq))
  expect_equal(as.character(sdbs),as.character(RNAStringSet(seq)))
  msdbs <- StructuredModRNAStringSet(seq,dbs)
  expect_s4_class(msdbs,"StructuredModRNAStringSet")
  expect_s4_class(sdbs,"StructuredXStringSet")
  expect_s4_class(msdbs,"StructuredXStringSet")
  expect_s4_class(sdbs[[1]],"RNAString")
  expect_s4_class(msdbs[[1]],"ModRNAString")
  expect_s4_class(dotbracket(sdbs),"DotBracketStringSet")
  # StructuredXStringSet
  file <- tempfile()
  writeStructuredXStringSet(sdbs,file)
  sdbs2 <- readStructuredRNAStringSet(file)
  expect_s4_class(sdbs2,"StructuredRNAStringSet")
  expect_equal(sdbs,sdbs2)
  writeStructuredXStringSet(msdbs,file)
  sdbs2 <- readStructuredRNAStringSet(file)
  expect_s4_class(sdbs2,"StructuredRNAStringSet")
  expect_equal(sdbs,sdbs2)
  # msdbs2 <- readStructuredModRNAStringSet(file)
  # expect_s4_class(msdbs2,"StructuredModRNAStringSet")
  # expect_equal(msdbs,msdbs2)
})
